name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Change files
      run: python3 updater.py
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
